/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class AssetUrls extends SpeakeasyBase {
  /**
   * URL of the descriptive asset. Using this dynamic asset will make sure that any copy update of Klarna will automatically be propagated.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "descriptive" })
  descriptive?: string;

  /**
   * URL of the standard asset. Using this dynamic asset will make sure that any copy update of Klarna will automatically be propagated.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "standard" })
  standard?: string;
}
