/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Attachment extends SpeakeasyBase {
  /**
   * The content of the extra merchant data should be presented as a string inside this property. The body should be an object containing any of the keys and sub-objects described below serialized to JSON. More information on that object can be found [here](https://developers.klarna.com/api/#attachment-schema).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "body" })
  body: string;

  /**
   * The content type of the body. It is usually represented as "application/vnd.klarna.internal.emd-v2+json"
   */
  @SpeakeasyMetadata()
  @Expose({ name: "content_type" })
  contentType: string;
}
