/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum AuthorizedPaymentMethodTypeEnum {
  Invoice = "invoice",
  FixedAmount = "fixed_amount",
  BaseAccount = "base_account",
  DirectDebit = "direct_debit",
  DirectBankTransfer = "direct_bank_transfer",
  B2bInvoice = "b2b_invoice",
  Card = "card",
  SliceItByCard = "slice_it_by_card",
  PayLaterByCard = "pay_later_by_card",
  PayByCard = "pay_by_card",
  FixedSumCredit = "fixed_sum_credit",
  AlternativePaymentMethod = "alternative_payment_method",
}

export class AuthorizedPaymentMethod extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "number_of_days" })
  numberOfDays?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "number_of_installments" })
  numberOfInstallments?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: AuthorizedPaymentMethodTypeEnum;
}
