/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Organization entity type. Only applicable for B2B customers.
 */
export enum CustomerOrganizationEntityTypeEnum {
  LimitedCompany = "LIMITED_COMPANY",
  PublicLimitedCompany = "PUBLIC_LIMITED_COMPANY",
  EntrepreneurialCompany = "ENTREPRENEURIAL_COMPANY",
  LimitedPartnershipLimitedCompany = "LIMITED_PARTNERSHIP_LIMITED_COMPANY",
  LimitedPartnership = "LIMITED_PARTNERSHIP",
  GeneralPartnership = "GENERAL_PARTNERSHIP",
  RegisteredSoleTrader = "REGISTERED_SOLE_TRADER",
  SoleTrader = "SOLE_TRADER",
  CivilLawPartnership = "CIVIL_LAW_PARTNERSHIP",
  PublicInstitution = "PUBLIC_INSTITUTION",
  Other = "OTHER",
}

export class Customer extends SpeakeasyBase {
  /**
   * Customer’s date of birth. The format is ‘yyyy-mm-dd’
   */
  @SpeakeasyMetadata()
  @Expose({ name: "date_of_birth" })
  dateOfBirth?: string;

  /**
   * Customer’s gender - ‘male’ or ‘female’
   */
  @SpeakeasyMetadata()
  @Expose({ name: "gender" })
  gender?: string;

  /**
   * Last four digits of the customer's social security number. This value is available for US customers.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "last_four_ssn" })
  lastFourSsn?: string;

  /**
   * The customer's national identification number. This value is available for EU customers utilizing national identification numbers.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "national_identification_number" })
  nationalIdentificationNumber?: string;

  /**
   * Organization entity type. Only applicable for B2B customers.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "organization_entity_type" })
  organizationEntityType?: CustomerOrganizationEntityTypeEnum;

  /**
   * Organization registration id. Only applicable for B2B customers.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "organization_registration_id" })
  organizationRegistrationId?: string;

  /**
   * Customer’s Title. Allowed values per country:
   *
   * @remarks
   * UK - "Mr", "Ms"
   * DE - "Herr", "Frau"
   * AT: "Herr, "Frau"
   * CH: de-CH: "Herr, "Frau" it-CH: "Sig.", "Sig.ra" fr-CH: "M", "Mme"
   * BE: "Dhr.", "Mevr."
   * NL: "Dhr.", "Mevr."
   */
  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title?: string;

  /**
   * Type of customer in the session. If nothing is added, a B2C session will be the default. If it is a b2b-session, you should enter organization to trigger a B2B session.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type?: string;

  /**
   * VAT ID. Only applicable for B2B customers.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "vat_id" })
  vatId?: string;
}
