/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class MerchantUrls extends SpeakeasyBase {
  /**
   * URL for receiving the authorization token when payment is completed. Used for Authorization Callback.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "authorization" })
  authorization?: string;

  /**
   * URL of the merchant confirmation page. The consumer will be redirected back to the confirmation page if the consumer is sent to the redirect URL after placing the order. Insert {session.id} and/or {order.id} as placeholder to connect either of those IDs to the URL(max 2000 characters).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "confirmation" })
  confirmation?: string;

  /**
   * URL for notifications on pending orders. Insert {session.id} and/or {order.id} as placeholder to connect either of those IDs to the URL (max 2000 characters).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "notification" })
  notification?: string;

  /**
   * URL that will be requested when an order is completed. Should be different than checkout and confirmation URLs. Insert {session.id} and/or {order.id} as placeholder to connect either of those IDs to the URL (max 2000 characters).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "push" })
  push?: string;
}
