/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PaymentMethodCategory } from "./paymentmethodcategory";
import { Expose, Type } from "class-transformer";

/**
 * successful operation
 */
export class MerchantSession extends SpeakeasyBase {
  /**
   * Client token to be passed to the JS client while initializing the JS SDK in the next step.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "client_token" })
  clientToken: string;

  /**
   * Available payment method categories for this particular session
   */
  @SpeakeasyMetadata({ elemType: PaymentMethodCategory })
  @Expose({ name: "payment_method_categories" })
  @Type(() => PaymentMethodCategory)
  paymentMethodCategories?: PaymentMethodCategory[];

  /**
   * ID of the created session. Please use this ID to share with Klarna for identifying any issues during integration.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "session_id" })
  sessionId: string;
}
