/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ProductIdentifiers extends SpeakeasyBase {
  /**
   * The product's brand name as generally recognized by consumers. If no brand is available for a product, do not supply any value.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "brand" })
  brand?: string;

  /**
   * The product's category path as used in the merchant's webshop. Include the full and most detailed category and separate the segments with ' > '
   */
  @SpeakeasyMetadata()
  @Expose({ name: "category_path" })
  categoryPath?: string;

  /**
   * Color to be shown to the end customer (max 64 characters).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "color" })
  color?: string;

  /**
   * The product's Global Trade Item Number (GTIN). Common types of GTIN are EAN, ISBN or UPC. Exclude dashes and spaces, where possible
   */
  @SpeakeasyMetadata()
  @Expose({ name: "global_trade_item_number" })
  globalTradeItemNumber?: string;

  /**
   * The product's Manufacturer Part Number (MPN), which - together with the brand - uniquely identifies a product. Only submit MPNs assigned by a manufacturer and use the most specific MPN possible
   */
  @SpeakeasyMetadata()
  @Expose({ name: "manufacturer_part_number" })
  manufacturerPartNumber?: string;

  /**
   * Size to be shown to the end customer (max 64 characters).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "size" })
  size?: string;
}
