/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The cadence unit for this.
 */
export enum SubscriptionIntervalEnum {
  Day = "DAY",
  Week = "WEEK",
  Month = "MONTH",
  Year = "YEAR",
}

export class Subscription extends SpeakeasyBase {
  /**
   * The cadence unit for this.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "interval" })
  interval: SubscriptionIntervalEnum;

  /**
   * The number of intervals
   */
  @SpeakeasyMetadata()
  @Expose({ name: "interval_count" })
  intervalCount: number;

  /**
   * The name of the subscription product
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;
}
