/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class CreateOrderRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=authorizationToken",
  })
  authorizationToken: string;

  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  createOrderRequestInput?: shared.CreateOrderRequestInput;
}

export class CreateOrderResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Order was successfully created.
   */
  @SpeakeasyMetadata()
  order?: shared.Order;
}
