/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class PurchaseTokenRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=authorizationToken",
  })
  authorizationToken: string;

  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  customerTokenCreationRequest?: shared.CustomerTokenCreationRequest;
}

export class PurchaseTokenResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * We were unable to create a customer token with the provided data. Some field constraint was violated.
   */
  @SpeakeasyMetadata()
  errorV2?: shared.ErrorV2;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Token was successfully created.
   */
  @SpeakeasyMetadata()
  customerTokenCreationResponse?: shared.CustomerTokenCreationResponse;
}
