/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ReadCreditSessionRequest extends SpeakeasyBase {
  /**
   * session_id
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=session_id",
  })
  sessionId: string;
}

export class ReadCreditSessionResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * successful operation
   */
  @SpeakeasyMetadata()
  sessionRead?: shared.SessionRead;
}
