/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateCreditSessionRequest extends SpeakeasyBase {
  /**
   * session_request
   */
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  sessionInput: shared.SessionInput;

  /**
   * session_id
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=session_id",
  })
  sessionId: string;
}

export class UpdateCreditSessionResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
